USE ROLE ACCOUNTADMIN;

-- Compute + cost guardrail
CREATE WAREHOUSE IF NOT EXISTS TRANSFORM_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;

CREATE RESOURCE MONITOR IF NOT EXISTS PORTFOLIO_RM WITH CREDIT_QUOTA = 20
  TRIGGERS ON 80 PERCENT DO NOTIFY ON 100 PERCENT DO SUSPEND;
ALTER WAREHOUSE TRANSFORM_WH SET RESOURCE_MONITOR = PORTFOLIO_RM;

-- Role for all pipeline work
CREATE ROLE IF NOT EXISTS TRANSFORMER;
GRANT ROLE TRANSFORMER TO ROLE SYSADMIN;
GRANT ROLE TRANSFORMER TO USER VCONCEP;  
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE TRANSFORMER;

-- Databases
CREATE DATABASE IF NOT EXISTS RAW;
CREATE DATABASE IF NOT EXISTS ANALYTICS;
GRANT OWNERSHIP ON DATABASE RAW TO ROLE TRANSFORMER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE ANALYTICS TO ROLE TRANSFORMER COPY CURRENT GRANTS;

USE ROLE TRANSFORMER;
USE WAREHOUSE TRANSFORM_WH;
CREATE SCHEMA IF NOT EXISTS RAW.NYC_TAXI;