USE ROLE ACCOUNTADMIN;

CREATE STORAGE INTEGRATION IF NOT EXISTS S3_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::136589556063:role/snowflake-s3-role'
  STORAGE_ALLOWED_LOCATIONS = ('s3://vconcep-nyc-taxi-raw/');

GRANT USAGE ON INTEGRATION S3_INT TO ROLE TRANSFORMER;

DESC INTEGRATION S3_INT;
USE ROLE TRANSFORMER;
USE WAREHOUSE TRANSFORM_WH;
USE SCHEMA RAW.NYC_TAXI;

CREATE FILE FORMAT IF NOT EXISTS PARQUET_FF TYPE = PARQUET;

CREATE STAGE IF NOT EXISTS NYC_TAXI_STAGE
  URL = 's3://vconcep-nyc-taxi-raw/nyc_taxi/'
  STORAGE_INTEGRATION = S3_INT
  FILE_FORMAT = PARQUET_FF;

LIST @NYC_TAXI_STAGE;
